package es.elv.kobold

object SoundDistance {
	val MeterToFeet = 3.2808399f
	val FeetToMeter = 0.3048f

	val WhisperVolume =  5.0f  * MeterToFeet
	val TalkVolume    =  30.0f * MeterToFeet
}

object BaseItem {
	val Amulet = 19
	val Armor = 16
	val Arrow = 20
	val BastardSword = 3
	val Battleaxe = 2
	val Belt = 21
	val BlankMagicWand = 103
	val BlankScroll = 102
	val Bolt = 25
	val Book = 74
	val Boots = 26
	val Bracer = 78
	val Bullet = 27
	val CreatureBludgeonWeapon = 71
	val Cloak = 80
	val Club = 28
	val CreaturePierceWeapon = 70
	val CraftBase = 112
	val CraftCompBase = 109
	val CraftCompSmall = 110
	val CraftedMagicWand = 106
	val CraftedPotion = 104
	val CraftedScroll = 105
	val CreatureItem = 73
	val CreatureSlashWeapon = 69
	val CreatureSlashPierceWeapon = 72
	val Dagger = 22
	val Dart = 31
	val DireMace = 32
	val DoubleAxe = 33
	val DwarvenWaraxe = 108
	val EmptyPotion = 101
	val Encampment = 82
	val Gem = 77
	val Gloves = 36
	val Gold = 76
	val Greataxe = 18
	val GreatSword = 13
	val Grenade = 81
	val Halberd = 10
	val Handaxe = 38
	val HealersKit = 39
	val HeavyCrossbow = 6
	val HeavyFlail = 35
	val Helmet = 17
	val Kama = 40
	val Katana = 41
	val Key = 65
	val Kukri = 42
	val Lance = 92
	val LargeBox = 66
	val LargeShield = 56
	val LightCrossbow = 7
	val LightFlail = 4
	val LightHammer = 37
	val LightMace = 9
	val Longbow = 8
	val Longsword = 1
	val MagicRod = 44
	val MagicStaff = 45
	val MagicWand = 46
	val MiscLarge = 34
	val MiscMedium = 29
	val MiscSmall = 24
	val MiscThin = 79
	val MoonOnAStick = 94
	val Morningstar = 47
	val Potion = 49
	val Quarterstaff = 50
	val Rapier = 51
	val Ring = 52
	val Scimitar = 53
	val Scythe = 55
	val Shortbow = 11
	val ShortSpear = 58
	val ShortSword = 0
	val Shuriken = 59
	val Sickle = 60
	val Sling = 61
	val SmallShield = 14
	val SpellScroll = 75
	val ThievesTools = 62
	val ThrowingAxe = 63
	val Torch = 15
	val TowerShield = 57
	val TrapKit = 64
	val Trident = 95
	val Trumpet = 93
	val TwobladedSword = 12
	val Warhammer = 5
	val Whip = 111
}
